### ISSUE TITLE
Kanban Review

### ISSUE THREAD

**Issue by PedroH-Neves** [PedroH-Neves/catalog-of-things#14]
GitHub Project

- https://github.com/PedroH-Neves/catalog-of-things/projects/1

It is just me in my Group

- PedroH-Neves

![image](https://github.com/PedroH-Neves/catalog-of-things/assets/85895404/82b50c2f-9556-442f-9feb-07ea6edb814e)

**Comment by Ibizugbe** [comment]
Hi @PedroH-Neves 👋🏼👋🏼👋🏼👋🏼, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] Link to kanban board has been provided👍🏼.
- [x] All required tasks are captured in the kanban board👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
